/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f4faff',
        'surface-dim': '#cfdce4',
        'surface-bright': '#f4faff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#e9f6fd',
        'surface-container': '#e3f0f8',
        'surface-container-high': '#ddeaf2',
        'surface-container-highest': '#d7e4ec',
        'on-surface': '#111d23',
        'on-surface-variant': '#5a4044',
        'inverse-surface': '#263238',
        'inverse-on-surface': '#e6f3fb',
        outline: '#8e6f74',
        'outline-variant': '#e3bdc3',
        'surface-tint': '#bc004f',
        primary: '#b0004a',
        'on-primary': '#ffffff',
        'primary-container': '#d81b60',
        'on-primary-container': '#fff2f3',
        'inverse-primary': '#ffb2bf',
        secondary: '#625f4f',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e0cc',
        'on-secondary-container': '#666353',
        tertiary: '#00616d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#007c8b',
        'on-tertiary-container': '#e2faff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffd9de',
        'primary-fixed-dim': '#ffb2bf',
        'on-primary-fixed': '#3f0016',
        'on-primary-fixed-variant': '#90003b',
        'secondary-fixed': '#e8e2cf',
        'secondary-fixed-dim': '#ccc6b4',
        'on-secondary-fixed': '#1e1c10',
        'on-secondary-fixed-variant': '#4a4739',
        'tertiary-fixed': '#9cf0ff',
        'tertiary-fixed-dim': '#00daf3',
        'on-tertiary-fixed': '#001f24',
        'on-tertiary-fixed-variant': '#004f58',
        background: '#f4faff',
        'on-background': '#111d23',
        'surface-variant': '#d7e4ec',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        gutter: '24px',
        base: '8px',
        'container-max': '1280px',
      },
      fontFamily: {
        'label-mono': ['JetBrains Mono', 'monospace'],
        'headline-xl': ['Bricolage Grotesque', 'system-ui'],
        'headline-lg': ['Bricolage Grotesque', 'system-ui'],
        'headline-lg-mobile': ['Bricolage Grotesque', 'system-ui'],
        'body-md': ['DM Sans', 'system-ui'],
        'sticker-text': ['Bricolage Grotesque', 'system-ui'],
      },
      fontSize: {
        'label-mono': ['12px', { lineHeight: '1.5', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'sticker-text': ['14px', { lineHeight: '1', fontWeight: '700' }],
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { filter: 'drop-shadow(0 0 8px rgba(0, 218, 243, 0.4))' },
          '50%': { filter: 'drop-shadow(0 0 15px rgba(0, 218, 243, 0.8))' },
        },
        float: {
          '0%': { transform: 'translateY(0px) rotate(0deg)', opacity: '0.2' },
          '50%': { transform: 'translateY(-20px) rotate(180deg)', opacity: '0.5' },
          '100%': { transform: 'translateY(0px) rotate(360deg)', opacity: '0.2' },
        },
      },
      animation: {
        glow: 'pulse-glow 3s infinite ease-in-out',
        float: 'float 15s infinite ease-in-out',
      },
      boxShadow: {
        hard: '4px 4px 0px 0px rgba(176,0,74,1)',
        hardblack: '4px 4px 0px 0px rgba(0,0,0,1)',
      },
    },
  },
  plugins: [forms],
};
